<?xml version='1.0' encoding='utf-8'?>
<test-data>

    <test-code>
        <description>bad 1</description>
        <expected-problems>1</expected-problems>
        <code>
// throwing various types
public class Foo {
    void bar() {
        throw new NullPointerException();
    }
}</code>
    </test-code>

    <test-code>
        <description>ok 1</description>
        <expected-problems>0</expected-problems>
        <code>
// no problems if NullPointerException is only instantiated but not thrown
public class Foo {
    void bar() {
        Exception e = new NullPointerException("Test message");
        String msg = e.getMessage();
    }
}</code>
    </test-code>

    <test-code>
        <description>bad 2</description>
        <expected-problems>1</expected-problems>
        <code>
// problem should be detected even if NullPointerException is stored in some intermediate variable
public class Foo {
    void bar() {
        Exception e = new NullPointerException();
        throw e;
    }
}</code>
    </test-code>

    <test-code>
        <description>ok 2</description>
        <expected-problems>0</expected-problems>
        <code>
// variables with same name false positive test
public class Foo {
    void foo() {
        Exception e = new NullPointerException();
        e.printStackTrace();
    }

    void bar() {
        Exception e = new RuntimeException();
        throw e;
    }
}</code>
    </test-code>

    <test-code>
        <description>ok 3</description>
        <expected-problems>0</expected-problems>
        <code>
// ok, variable has been reassigned to RuntimeException before thrown
public class Foo {
    void bar() {
        Exception e = new NullPointerException();
        e = new RuntimeException();
        throw e;
    }
}</code>
    </test-code>

    <test-code>
        <description>ok 4</description>
        <expected-problems>0</expected-problems>
        <code>
// ok, variable is reassigned with NullPointerException after thrown
public class Foo {
    void bar(String s) {
        Exception e = new RuntimeException();
        if (s.equals("throw")) {
            throw e;
        }
        e = new NullPointerException();
    }
}</code>
    </test-code>

    <test-code>
        <description>bad 3</description>
        <expected-problems>1</expected-problems>
        <code>
// bad, variable had been reassigned with NullPointerException before thrown
public class Foo {
    void bar() {
        Exception e = new RuntimeException();
        e = new NullPointerException();
        throw e;
    }
}</code>
    </test-code>
    <test-code>
        <description>ok 5</description>
        <expected-problems>0</expected-problems>
        <code>
// variable is not necessarily an NPE
public class Foo {
    void bar() {
        Exception e = new RuntimeException();
        if (e.toString().isEmpty())
            e = new NullPointerException();
        throw e;
    }
}</code>
    </test-code>
    <test-code>
        <description>ok 6</description>
        <expected-problems>0</expected-problems>
        <code>
// variable is not necessarily an NPE 2
public class Foo {
    void bar(Exception e) {
        if (e.toString().isEmpty())
            e = new NullPointerException();
        throw e;
    }
}</code>
    </test-code>
</test-data>